### ISSUE TITLE
Dataset Release

### ISSUE THREAD

**Issue by DachunKai** [yunfanLu/INR-Event-VSR#5]
Have you finished uploading the collected dataset? Thanks.

**Comment by yunfanLu** [comment]
https://www.alpsentek.com/product

Sorry, the dataset is not uploading right now. Our data needs to be redacted of some sensitive information with the help of sponsors, as the sensors that captured the dataset are not publicly available yet.

**Comment by ksoy0128** [comment]
1. When will the dataset be released? Is there a commercially available dataset to evaluate the performance of this code before the dataset is released?
2. Do you provide pretrained models for datasets such as CED? If so, I'd like to know how to use it.

**Comment by yunfanLu** [comment]
Thank you for your interest.

 I will talk to our sponsor, and I will ask to make the data public as soon as possible because I also know that CVPR 2024 is coming soon.

Regarding the second question, I'll write documentation for code usage and scripts to help you to use the pre-trained model.  I would also like you to try running the code now, it already can do what you need to do.

**Comment by yunfanLu** [comment]
Thank you for your interest in this project; I have uploaded the dataset to the network disk (in README.md). 
Hope this helps. Please feel free to contact me if you have any questions.
