### ISSUE TITLE
Run code w. CED dataset

### ISSUE THREAD

**Issue by ksoy0128** [yunfanLu/INR-Event-VSR#6]
There are several problems with running the code w. CED dataset.

1) Is the .yaml file in the "options/CED" folder the latest version? In the file, (1) the dataset is specified as ALPX,
and (2) the code does not run because the "config.is_mini" is not set in the option file.
How can I set config.is_mini?

2) If I set MOMENTS to 36 in the .yaml file of "CED dataset", I get an error. But if I set MOMENTS to 18, the code seems to work. Could you please upload the final version of the .yaml file for the CED dataset?

3) I wonder what the low resolution (input size) is at x2, x4 @CED. Looking at the code, the final resolution seems to be fixed at 260*340. To see the x2 SR result, can I set the low resolution to 260//2, 340//2? (In case of x4, 260//4 and 340//4 are input)

4) If TEST_ONLY is set to True, can I download the pre-trained model? When I checked, there doesn't seem to be a pre-trained model available.

Thanks :)

**Comment by yunfanLu** [comment]
Dear ksoy0128,

Thank you for your interest in this project.

1.  `is_mini` is used to filter datasets. For details, you can refer to the code [here](https://github.com/yunfanLu/INR-Event-VSR/blame/main/egvsr/datasets/color_event_dataset.py#L132-L139). Setting up variables allows you to sift through a smaller data set and validate your ideas because training on the full dataset can take a week.  
2. You are right because each moment has positive and negative channels when splitting events.
3. You are right. You can refer to the code [here](https://github.com/yunfanLu/INR-Event-VSR/blame/main/egvsr/datasets/color_event_dataset.py#L125)
4. Sorry, I don't have a server that can support downloading the pre-trained model. I will put the pre-trained model on the network disk and share it with you.

Thank you again for your attention, and I hope to answer your questions. 
If you have other questions, please feel free to contact me.

Thanks :)
