### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by Rtakaha** [yunfanLu/INR-Event-VSR#7]
Hi, Could you tell me what license is applied to the code and the dataset?

Thank you.

**Comment by yunfanLu** [comment]
Thank you for your attention. I am happy that my code can help you. I have no claims to this public code and you can use it as you like. If it can help with your research, then I will be happy, because much of the code in my project comes from other open-source codes. If the community accepts your research, it is best to open-source it and help more people. Of course, this is not mandatory.

**Comment by Rtakaha** [comment]
Thank you!
